#!/bin/bash

. /etc/minios/config

case "${DISTRIBUTION}" in
stretch | buster | bullseye | bookworm | trixie | sid)
    DISTRIBUTION_TYPE="debian"
    ;;
bionic | focal | jammy | noble)
    DISTRIBUTION_TYPE="ubuntu"
    ;;
esac

if [ "${DISTRIBUTION_TYPE}" = "debian" ]; then
    FIREFOX_BRANDING="/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js"
elif [ "${DISTRIBUTION_TYPE}" = "ubuntu" ]; then
    FIREFOX_BRANDING="/etc/firefox/syspref.js"
fi

if [ -f "${FIREFOX_BRANDING}" ] && [ ! -f "${FIREFOX_BRANDING}.bak" ] && ! grep -q minios "${FIREFOX_BRANDING}"; then
    cp "${FIREFOX_BRANDING}" "${FIREFOX_BRANDING}.bak"
    if [ "${DISTRIBUTION_TYPE}" = "debian" ]; then
        sed -i "s,about:welcome,file:///usr/share/minios/html/index.html,g" "${FIREFOX_BRANDING}"
    elif [ "${DISTRIBUTION_TYPE}" = "ubuntu" ]; then
        cat <<EOF >>"${FIREFOX_BRANDING}"
pref("startup.homepage_welcome_url", "file:///usr/share/minios/html/index.html");
EOF
    fi
    if [[ "${DESKTOP_ENVIRONMENT}" == *"flux"* ]]; then
        cat <<'EOF' >>"${FIREFOX_BRANDING}"
pref("general.smoothScroll", false);
pref("browser.uidensity", 1);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.toolbars.bookmarks.visibility", "never");
EOF
    else
        cat <<'EOF' >>"${FIREFOX_BRANDING}"
pref("browser.tabs.drawInTitlebar", true);
pref("general.smoothScroll", false);
pref("browser.compactmode.show", true);
pref("browser.uidensity", 1);
pref("browser.tabs.inTitlebar", 1);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.toolbars.bookmarks.visibility", "never");
EOF
    fi
fi

#DEBHELPER#
