#!/bin/bash

if [ -f "/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js" ]; then
    FIREFOX_BRANDING="/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js"
elif [ -f "/etc/firefox/syspref.js" ]; then
    FIREFOX_BRANDING="/etc/firefox/syspref.js"
fi

if [ -f "${FIREFOX_BRANDING}.bak" ] && [ -f "${FIREFOX_BRANDING}" ] && grep -q minios "${FIREFOX_BRANDING}"; then
    mv -f "${FIREFOX_BRANDING}.bak" "${FIREFOX_BRANDING}"
fi

#DEBHELPER#
